import type { DeploykitConfig } from "../config.js";
import { PKG } from "../util/pkg.js";

/**
 * The source-of-truth `deploykit.config.ts`. Everything else is regenerable
 * from this file, and the user owns it. Emitted as a `defineConfig(...)` call
 * with the resolved config serialized as a literal.
 */
export function generateConfigFile(config: DeploykitConfig): string {
  const body = JSON.stringify(config, null, 2);
  return `import { defineConfig } from "${PKG.name}";

// Generated by \`deploykit init\` — the source of truth for your CI/CD setup.
// Edit this file (keep it JSON-style), then run \`deploykit generate\` to
// regenerate the Dockerfiles, fly.toml files and workflow from it.
export default defineConfig(${body});
`;
}
