import type { DeploykitConfig } from "../config.js";

/**
 * The source-of-truth `deploykit.config.ts`. Everything else is regenerable
 * from this file, and the user owns it. Emitted as a `defineConfig(...)` call
 * with the resolved config serialized as a literal.
 */
export function generateConfigFile(config: DeploykitConfig): string {
  const body = JSON.stringify(config, null, 2);
  return `import { defineConfig } from "deploykit";

// Generated by \`deploykit init\` — the record of your CI/CD setup.
// Edit the generated Dockerfiles / workflow directly (you own them), or
// re-run \`deploykit init --force\` to regenerate everything from scratch.
export default defineConfig(${body});
`;
}
