/**
 * A single root-level .dockerignore. The build context is always the repo root
 * (turbo prune needs the whole workspace to compute the pruned subset), so the
 * ignore file belongs at the root, not per app.
 *
 * It must NOT exclude app/package source — only junk and build artifacts.
 */
export function generateDockerignore(): string {
  return `# Generated by deploykit.
**/node_modules
**/.next
**/dist
**/build
**/.turbo
**/.cache

.git
.github
.vscode

**/*.log
**/.DS_Store

# Never ship real secrets into the image; keep the example.
**/.env
**/.env.*
!**/.env.example

Dockerfile
**/Dockerfile
.dockerignore
`;
}
