import type { PackageManager } from "../config.js";
import type { GenerateAppFileInput } from "./types.js";

interface PmCommands {
  /** Run a package binary without a prior install (used for `turbo prune`). */
  dlx: string;
  /** Install from the pruned lockfile. */
  install: string;
  /** Run the workspace build for one package. */
  build: (filter: string) => string;
  /** Start command for a long-running server app. */
  start: string[];
}

const PM: Record<PackageManager, PmCommands> = {
  pnpm: {
    dlx: "pnpm dlx",
    install: "pnpm install --frozen-lockfile",
    build: (f) => `pnpm turbo run build --filter=${f}`,
    start: ["pnpm", "start"],
  },
  npm: {
    dlx: "npx --yes",
    install: "npm install",
    build: (f) => `npx turbo run build --filter=${f}`,
    start: ["npm", "start"],
  },
  yarn: {
    dlx: "yarn dlx",
    install: "yarn install --frozen-lockfile",
    build: (f) => `yarn turbo run build --filter=${f}`,
    start: ["yarn", "start"],
  },
  bun: {
    dlx: "bunx",
    install: "bun install",
    build: (f) => `bunx turbo run build --filter=${f}`,
    start: ["bun", "start"],
  },
};

/**
 * A multi-stage, monorepo-aware Dockerfile.
 *
 * The build context is the repo root; `turbo prune --docker` isolates just this
 * app plus its internal workspace deps so the install layer caches properly.
 * The runner stage is framework-specific.
 */
export function generateDockerfile({ name, app, config }: GenerateAppFileInput) {
  const pm = PM[config.packageManager];
  const node = `node:${config.nodeVersion}-slim`;
  const filter = app.packageName;

  const head = `# syntax=docker/dockerfile:1
# Generated by deploykit — safe to edit and commit.
# Build context is the repo ROOT, e.g.:
#   flyctl deploy . --config ${app.root}/fly.toml --dockerfile ${app.root}/Dockerfile --app <app>

FROM ${node} AS base
ENV PNPM_HOME="/pnpm" PATH="/pnpm:$PATH"
RUN corepack enable || true

# ── prune: isolate ${name} + its workspace deps ──────────────────────────────
FROM base AS prune
WORKDIR /app
COPY . .
RUN ${pm.dlx} turbo prune ${filter} --docker

# ── install + build ──────────────────────────────────────────────────────────
FROM base AS build
WORKDIR /app
# Lockfile + package manifests first for a cacheable install layer.
COPY --from=prune /app/out/json/ .
RUN ${pm.install}
# Then the pruned source, and build.
COPY --from=prune /app/out/full/ .
RUN ${pm.build(filter)}
`;

  return head + "\n" + runnerStage({ name, app, config }) + "\n";
}

function runnerStage({ name, app, config }: GenerateAppFileInput) {
  const node = `node:${config.nodeVersion}-slim`;
  const pm = PM[config.packageManager];
  const { root, port, framework } = app;

  const header = `# ── runner ───────────────────────────────────────────────────────────────────
FROM ${node} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
RUN addgroup --system --gid 1001 nodejs \\
 && adduser --system --uid 1001 --ingroup nodejs appuser
EXPOSE ${port}`;

  if (framework === "next") {
    return `${header}

# Requires \`output: "standalone"\` in ${root}/next.config.{js,mjs,ts}.
COPY --from=build --chown=appuser:nodejs /app/${root}/.next/standalone ./
COPY --from=build --chown=appuser:nodejs /app/${root}/.next/static ./${root}/.next/static
COPY --from=build --chown=appuser:nodejs /app/${root}/public ./${root}/public
USER appuser
CMD ["node", "${root}/server.js"]
`;
  }

  if (framework === "remix" || framework === "node-server") {
    // Copy the built workspace and run the app's own start script.
    return `${header}

COPY --from=build --chown=appuser:nodejs /app ./
WORKDIR /app/${root}
USER appuser
CMD ${JSON.stringify(pm.start)}
`;
  }

  // static | vite | astro — serve the built output with a tiny static server.
  const spa = framework === "vite" ? " -s" : "";
  return `${header}

RUN npm install -g serve@14
COPY --from=build --chown=appuser:nodejs /app/${root}/dist ./dist
USER appuser
CMD ["serve"${spa ? `, "-s"` : ""}, "-l", "${port}", "dist"]
`;
}
