import type { DeploykitConfig, PackageManager } from "../config.js";

export interface PmCommands {
  /** Run a locally-installed binary: pnpm | npx | yarn | bunx. */
  run: string;
  /** Fetch and run a binary without a prior install (e.g. `turbo prune`). */
  dlx: string;
  /** Frozen install from the lockfile. */
  install: string;
  /** Production-only install (no lockfile assumed — used on pruned output). */
  installProd: string;
  /** Start command for a long-running server app. */
  start: string[];
}

export const PM: Record<PackageManager, PmCommands> = {
  pnpm: {
    run: "pnpm",
    dlx: "pnpm dlx",
    install: "pnpm install --frozen-lockfile",
    installProd: "pnpm install --prod",
    start: ["pnpm", "start"],
  },
  npm: {
    run: "npx",
    dlx: "npx --yes",
    install: "npm install",
    installProd: "npm install --omit=dev",
    start: ["npm", "start"],
  },
  yarn: {
    run: "yarn",
    dlx: "yarn dlx",
    install: "yarn install --frozen-lockfile",
    installProd: "yarn install --production",
    start: ["yarn", "start"],
  },
  bun: {
    run: "bunx",
    dlx: "bunx",
    install: "bun install",
    installProd: "bun install --production",
    start: ["bun", "start"],
  },
};

export const nodeImage = (config: DeploykitConfig) =>
  `node:${config.nodeVersion}-slim`;

/** Shared base stage: node image + corepack for pnpm/yarn. */
export const baseStage = (config: DeploykitConfig) => `FROM ${nodeImage(
  config,
)} AS base
ENV PNPM_HOME="/pnpm" PATH="/pnpm:$PATH"
RUN corepack enable || true`;

/** Shared runner-stage header: image, workdir, env, non-root user, port. */
export const runnerHeader = ({ node, port }: { node: string; port: number }) =>
  `# ── runner ───────────────────────────────────────────────────────────────────
FROM ${node} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${port}
RUN addgroup --system --gid 1001 nodejs \\
 && adduser --system --uid 1001 --ingroup nodejs appuser
EXPOSE ${port}`;

/** File header shared by both generators. */
export const fileHeader = ({ root, base }: { root: string; base: string }) =>
  `# syntax=docker/dockerfile:1
# Generated by deploykit — safe to edit and commit.
# Build context is the repo ROOT, e.g.:
#   flyctl deploy . --config ${root}/fly.toml --dockerfile ${root}/Dockerfile --app <app>

${base}`;
