/**
 * A single root-level .dockerignore. The build context is always the repo root
 * (turbo prune needs the whole workspace to compute the pruned subset), so the
 * ignore file belongs at the root, not per app.
 *
 * It must NOT exclude app/package source — only junk and build artifacts.
 */
export function generateDockerignore(): string {
  return `# Generated by deploykit.
**/node_modules
**/.next
**/dist
**/build
**/.turbo
**/.cache

.git
.github
.vscode

**/*.log
**/.DS_Store

# Never ship real secrets into the image; keep the example.
**/.env
**/.env.*
!**/.env.example

# deploykit's own plaintext credential/secret files (see src/secrets-file.ts).
# Gitignored already, but the Docker build context is the repo root, so they
# must be excluded here too — otherwise they upload to the remote builder and,
# for apps that COPY the whole context, bake into the shipped image.
.deploykit/

Dockerfile
**/Dockerfile
.dockerignore
`;
}
