import type { GenerateAppFileInput } from "./types.js";

/**
 * Per-app fly.toml. The `app` field is only a local default — CI always targets
 * the concrete per-environment app (web-staging, web-pr-42, …) with `--app`.
 */
export function generateFlyToml({ name, app, config }: GenerateAppFileInput) {
  return `# Generated by deploykit — safe to edit and commit.
# CI overrides the app name per environment via \`flyctl deploy --app <name>\`.
app = "${name}"
primary_region = "${config.provider.region}"

# Build context is the repo root; CI passes --dockerfile ${app.root}/Dockerfile.

[http_service]
  internal_port = ${app.port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
`;
}
