import type { AppConfig } from "../config.js";
import type { GenerateAppFileInput } from "./types.js";

/**
 * A COMMENTED-OUT `[deploy] release_command` for apps with a detected Prisma
 * schema — Fly's idiomatic per-release migration hook. Emitted only as guidance:
 * deploykit never runs migrations (a bad one causes irreversible data loss), so
 * it's inert until the user uncomments it against a database they own. Empty for
 * apps with no Prisma target, so their fly.toml is byte-for-byte unchanged.
 */
function migrationHint(app: AppConfig): string {
  const targets = app.prisma ?? [];
  if (targets.length === 0) return "";
  const cmd = targets
    .map(
      (t) =>
        `(cd ${t.root} && npx prisma migrate deploy${t.hasConfig ? "" : ` --schema ./${t.schema}`})`,
    )
    .join(" && ");
  return `# Database migrations: [deploy].release_command runs once per release,
# before new machines take traffic — the idiomatic place for migrations.
# deploykit generated this COMMENTED OUT and never runs it. Uncomment only
# against a database you own, and confirm the Prisma CLI + schema are present in
# the runtime image. A destructive migration here can cause irreversible data
# loss, and it is not undone by \`deploykit rollback\` (which reverts the image
# only). See the Database migrations section of the README.
# [deploy]
#   release_command = "${cmd}"

`;
}

/**
 * Per-app fly.toml. The `app` field is only a local default — CI always targets
 * the concrete per-environment app (web-staging, web-pr-42, …) with `--app`.
 */
export function generateFlyToml({ name, app, config }: GenerateAppFileInput) {
  const healthPath = app.healthCheckPath ?? "/";
  return `# Generated by deploykit — safe to edit and commit.
# CI overrides the app name per environment via \`flyctl deploy --app <name>\`.
app = "${name}"
primary_region = "${config.provider.region}"

# Build context is the repo root; CI passes --dockerfile ${app.root}/Dockerfile.

${migrationHint(app)}[http_service]
  internal_port = ${app.port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Health check: Fly waits for this to pass before shifting traffic to a new
  # release, and keeps the old machines running if it fails — auto-rollback on a
  # bad deploy. If "${healthPath}" 404s (e.g. an API with no root route), point
  # it at a lightweight endpoint via \`healthCheckPath\` in deploykit.config.ts.
  # grace_period is deliberately generous: a slow SSR cold-start on shared-cpu
  # shouldn't be mistaken for a bad release and block the deploy.
  [[http_service.checks]]
    method = "GET"
    path = "${healthPath}"
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
`;
}
