import type { DeploykitConfig, EnvironmentKind } from "../config.js";
import {
  type Destination,
  destinations,
  destinationsForApp,
  ENV_ORDER,
  TRIGGER_LABEL,
} from "../destinations.js";
import type { GithubRepo } from "../util/git.js";

/** Workflow file the generated links point at. Kept in sync with `planFiles`. */
const WORKFLOW_FILE = "deploy.yml";

/**
 * `DEPLOYMENTS.md` — the map of what got created and where to find it.
 *
 * The end-of-run terminal output only helps whoever ran `init`; this is the
 * same picture for everyone who arrives later, so it's a committed file rather
 * than an untracked one. It holds names, hostnames and dashboard links only —
 * never secret values.
 */
export function generateSummary({
  config,
  repo,
}: {
  config: DeploykitConfig;
  repo: GithubRepo | null;
}): string {
  const apps = Object.keys(config.apps);
  const sections = [
    header(),
    flowDiagram(config),
    ...apps.map((app) => appSection({ app, config })),
    dashboards({ config, repo }),
    secrets({ config, repo }),
    goodToKnow(config),
  ];
  return `${sections.filter(Boolean).join("\n\n")}\n`;
}

function header() {
  return `# Deployments

<!-- Generated by deploykit. Edit \`deploykit.config.ts\` and run \`deploykit generate\`
     to update this file — hand edits are overwritten. -->

Where every app runs, what deploys it, and where to click in each dashboard.`;
}

/**
 * A mermaid flow of trigger → environment. GitHub renders it inline, so the
 * shape of the pipeline is readable without running anything. Only the
 * environment kinds that are actually configured get a lane.
 */
function flowDiagram(config: DeploykitConfig): string {
  const present = ENV_ORDER.filter((kind) =>
    Object.values(config.apps).some((a) => a.environments[kind]),
  );
  if (present.length === 0) return "";

  const label = (kind: EnvironmentKind) => {
    const names = Object.entries(config.apps)
      .filter(([, a]) => a.environments[kind])
      .map(([name]) => name)
      .join(", ");
    return `${kind}<br/>${names}`;
  };

  const lines = ["```mermaid", "flowchart LR"];
  if (present.includes("preview")) {
    lines.push(`  pr["pull request"] --> preview["${label("preview")}"]`);
    lines.push(`  pr -. "PR closed" .-> destroy["apps destroyed"]`);
  }
  if (present.includes("staging")) {
    lines.push(`  main["merge to main"] --> staging["${label("staging")}"]`);
  }
  if (present.includes("production")) {
    const from = present.includes("staging") ? "staging" : "main";
    if (!present.includes("staging")) lines.push(`  main["merge to main"]`);
    lines.push(`  ${from} --> gate{"manual approval"}`);
    lines.push(`  gate --> production["${label("production")}"]`);
  }
  lines.push("```");
  return lines.join("\n");
}

/** Per-app table of every environment: URL, Fly app, and what deploys it. */
function appSection({
  app,
  config,
}: {
  app: string;
  config: DeploykitConfig;
}): string {
  const rows = destinationsForApp({ app, config });
  if (rows.length === 0) return "";
  const cfg = config.apps[app];
  const source = cfg ? ` — \`${cfg.root}\`` : "";

  const lines = [
    `## ${app}${source}`,
    "",
    "| Environment | URL | Fly app | Deploys |",
    "| --- | --- | --- | --- |",
  ];
  for (const d of rows) {
    lines.push(
      `| ${d.kind} | ${linkOrCode(d)} | \`${d.flyApp}\` | ${TRIGGER_LABEL[d.trigger]} |`,
    );
  }
  return lines.join("\n");
}

/**
 * Preview URLs carry a `{pr}` placeholder and aren't clickable, so they render
 * as code; concrete environments render as links.
 */
function linkOrCode(d: Destination): string {
  return d.flyApp.includes("{pr}") ? `\`${d.url}\`` : `<${d.url}>`;
}

/**
 * The section this file exists for: deep links into every console, so nobody
 * has to hunt an app down org by org.
 */
function dashboards({
  config,
  repo,
}: {
  config: DeploykitConfig;
  repo: GithubRepo | null;
}): string {
  const org = config.provider.org;
  const rows: [string, string][] = [
    [
      "Fly org — every app, billing, deploy tokens",
      `https://fly.io/dashboard/${org}`,
    ],
    [
      "Fly deploy token (`FLY_API_TOKEN`) — revoke/rotate here",
      `https://fly.io/dashboard/${org}/tokens`,
    ],
  ];

  // Preview apps are created on the fly by the workflow, so there's no stable
  // URL to link — only the long-lived environments get per-app rows.
  for (const d of destinations(config).filter(
    (x) => !x.flyApp.includes("{pr}"),
  )) {
    rows.push([
      `\`${d.flyApp}\` — overview`,
      `https://fly.io/apps/${d.flyApp}`,
    ]);
    rows.push([
      `\`${d.flyApp}\` — metrics & logs`,
      `https://fly.io/apps/${d.flyApp}/monitoring`,
    ]);
    rows.push([
      `\`${d.flyApp}\` — runtime secrets`,
      `https://fly.io/apps/${d.flyApp}/secrets`,
    ]);
  }

  const zone = config.cloudflare?.zone;
  if (zone) {
    // The `?to=/:account/…` form lets Cloudflare resolve the account id, so the
    // link works without knowing it.
    rows.push([
      `Cloudflare DNS — ${zone}`,
      `https://dash.cloudflare.com/?to=/:account/${zone}/dns`,
    ]);
    rows.push([
      `Cloudflare SSL/TLS — ${zone}`,
      `https://dash.cloudflare.com/?to=/:account/${zone}/ssl-tls`,
    ]);
  }

  if (repo) {
    rows.push([
      "GitHub Actions — deploy runs",
      `${repo.url}/actions/workflows/${WORKFLOW_FILE}`,
    ]);
    rows.push([
      "GitHub environments — approvals & env secrets",
      `${repo.url}/settings/environments`,
    ]);
    rows.push([
      "GitHub secrets — repository level",
      `${repo.url}/settings/secrets/actions`,
    ]);
  }

  const lines = ["## Where to look", "", "| What | Where |", "| --- | --- |"];
  for (const [what, url] of rows) lines.push(`| ${what} | <${url}> |`);
  if (!repo) {
    lines.push("");
    lines.push(
      "_No GitHub remote was found when this file was generated, so the GitHub links are omitted. Re-run `deploykit generate` once the remote is set._",
    );
  }
  return lines.join("\n");
}

/**
 * Which variables the pipeline expects and how each is wired — names only, so
 * this file stays safe to commit.
 */
function secrets({
  config,
  repo,
}: {
  config: DeploykitConfig;
  repo: GithubRepo | null;
}): string {
  interface Row {
    name: string;
    kind: "runtime" | "build-time";
    apps: string[];
  }
  const byName = new Map<string, Row>();
  const add = (name: string, kind: Row["kind"], app: string) => {
    const row = byName.get(name) ?? { name, kind, apps: [] };
    if (!row.apps.includes(app)) row.apps.push(app);
    byName.set(name, row);
  };
  for (const [app, cfg] of Object.entries(config.apps)) {
    for (const name of cfg.secrets) add(name, "runtime", app);
    for (const name of cfg.buildEnv ?? []) add(name, "build-time", app);
  }
  if (byName.size === 0) return "";

  const where = repo ? `${repo.url}/settings/secrets/actions` : null;
  const lines = [
    "## Secrets",
    "",
    `Values live in GitHub Actions secrets${where ? ` (<${where}>)` : ""} and are never stored in this repo. Set or update them with \`deploykit init\`, or in the GitHub UI.`,
    "",
    "| Name | Wired as | Used by |",
    "| --- | --- | --- |",
  ];
  for (const row of [...byName.values()].sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const wiring =
      row.kind === "runtime"
        ? "runtime — `flyctl secrets set`"
        : "build-time — baked into the image (`--build-arg`)";
    lines.push(`| \`${row.name}\` | ${wiring} | ${row.apps.join(", ")} |`);
  }
  lines.push("");
  lines.push(
    "Per-environment values (a staging vs production `DATABASE_URL`) go on the matching GitHub environment; anything set at the repository level applies to every environment that doesn't override it.",
  );
  return lines.join("\n");
}

/** The handful of facts that otherwise turn into "why isn't it there?" questions. */
function goodToKnow(config: DeploykitConfig): string {
  const items: string[] = [];
  const has = (kind: EnvironmentKind) =>
    Object.values(config.apps).some((a) => a.environments[kind]);

  if (has("preview")) {
    items.push(
      "**Preview apps don't exist until a PR opens.** The workflow creates them on first deploy and destroys them when the PR closes, so you won't find them on the Fly dashboard in between.",
    );
  }
  if (has("production")) {
    items.push(
      "**Production waits for a human.** It only deploys after the `production` GitHub environment is approved — add required reviewers there, or the gate approves itself.",
    );
  }
  if (config.cloudflare) {
    items.push(
      `**Custom domains resolve through Cloudflare.** DNS records point at Fly and the certificate is issued by Fly; the \`*.fly.dev\` address keeps working either way, which makes it the thing to test against when a domain looks wrong.`,
    );
  }
  items.push(
    "**A failed health check keeps the old release serving.** Fly only shifts traffic once the new machines pass their check, so a bad deploy stalls instead of taking the app down. To undo a release that passed but misbehaves, run `deploykit rollback`.",
  );
  items.push(
    "**Everything here is regenerable.** `deploykit.config.ts` is the source of truth — edit it and run `deploykit generate` to update the Dockerfiles, `fly.toml` files, the workflow, and this file.",
  );

  return ["## Good to know", "", ...items.map((i) => `- ${i}`)].join("\n");
}
