import {
  type DeploykitConfig,
  type EnvironmentKind,
  extraRegions,
} from "../config.js";

/** Render a GitHub Actions expression: gh("secrets.X") -> "${{ secrets.X }}". */
// biome-ignore lint/style/useTemplate: a template literal collides with the `${{` GitHub Actions delimiter
const gh = (expr: string) => "${{ " + expr + " }}";

export function generateWorkflow(config: DeploykitConfig): string {
  const apps = Object.entries(config.apps);
  const appNames = apps.map(([name]) => name);
  // Fly app names are global — the prefix (when configured) namespaces every
  // name this workflow creates or targets, previews included.
  const prefix = config.namePrefix ? `${config.namePrefix}-` : "";

  const hasPreview = apps.some(([, a]) => a.environments.preview);
  const hasStaging = apps.some(([, a]) => a.environments.staging);
  const hasProduction = apps.some(([, a]) => a.environments.production);
  const needChanges = hasPreview || hasStaging;

  const jobs: string[] = [];
  if (needChanges) jobs.push(changesJob(config));
  if (hasPreview)
    jobs.push(
      previewJob({ config, prefix }),
      teardownJob({ appNames, prefix }),
    );
  if (hasStaging) jobs.push(stagingJob({ config, prefix }));
  if (hasProduction) jobs.push(productionJob({ config, appNames, prefix }));

  return `# Generated by deploykit — CI/CD for a Turbo monorepo on Fly.io.
name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy to production'
        default: all
        type: choice
        options: ${JSON.stringify(["all", ...appNames])}

# Grouped per event so a production dispatch never shares a group with (and
# cancels) a staging push. Only PR runs are cancelled mid-flight — previews are
# disposable; staging/production deploys queue instead of dying mid-deploy.
concurrency:
  group: deploy-${gh("github.workflow")}-${gh("github.event_name")}-${gh("github.ref")}
  cancel-in-progress: ${gh("github.event_name == 'pull_request'")}

permissions:
  contents: read
  pull-requests: write
  issues: write # preview comments are issue comments (updated in place)

env:
  FLY_ORG: ${config.provider.org}

jobs:
${jobs.join("\n")}`;
}

// ── changes: compute which apps are affected ─────────────────────────────────
function changesJob(config: DeploykitConfig): string {
  const filters = Object.entries(config.apps)
    .map(([name, app]) => {
      const paths = app.watchPaths
        .map((p) => `              - '${p}'`)
        .join("\n");
      return `            ${name}:\n${paths}`;
    })
    .join("\n");

  return `  changes:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    outputs:
      apps: ${gh("steps.filter.outputs.changes")}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
${filters}
`;
}

// ── preview: deploy one app per PR ───────────────────────────────────────────
function previewJob({
  config,
  prefix,
}: {
  config: DeploykitConfig;
  prefix: string;
}): string {
  const flyApp = `"${prefix}$APP-pr-${gh("github.event.number")}"`;
  return `  preview:
    needs: changes
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && needs.changes.outputs.apps != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${gh("fromJSON(needs.changes.outputs.apps)")}
    concurrency:
      group: preview-${gh("github.event.number")}-${gh("matrix.app")}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "preview", flyAppExpr: flyApp, singleMachine: true })}
      - name: Comment preview URL
        env:
          GH_TOKEN: ${gh("secrets.GITHUB_TOKEN")}
        # Upsert (via a hidden per-app marker) so repeated pushes update one
        # comment instead of stacking a new one per deploy.
        run: |
          APP="${gh("matrix.app")}"
          URL="https://${prefix}$APP-pr-${gh("github.event.number")}.fly.dev"
          MARKER="<!-- deploykit-preview:$APP -->"
          BODY=$(printf '🚀 Preview for \`%s\`: %s\\n\\n%s' "$APP" "$URL" "$MARKER")
          COMMENT_ID=$(gh api "repos/${gh("github.repository")}/issues/${gh("github.event.number")}/comments" \\
            --paginate --jq ".[] | select(.body | contains(\\"$MARKER\\")) | .id" | head -n1)
          if [ -n "$COMMENT_ID" ]; then
            gh api --method PATCH "repos/${gh("github.repository")}/issues/comments/$COMMENT_ID" -f body="$BODY" >/dev/null
          else
            gh pr comment ${gh("github.event.number")} --repo ${gh("github.repository")} --body "$BODY"
          fi
`;
}

// ── teardown: destroy preview apps when the PR closes ────────────────────────
function teardownJob({
  appNames,
  prefix,
}: {
  appNames: string[];
  prefix: string;
}): string {
  return `  teardown:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${JSON.stringify(appNames)}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destroy preview
        env:
          FLY_API_TOKEN: ${gh("secrets.FLY_API_TOKEN")}
        run: |
          flyctl apps destroy "${prefix}${gh("matrix.app")}-pr-${gh("github.event.number")}" --yes || true
`;
}

// ── staging: deploy affected apps on merge to main ───────────────────────────
function stagingJob({
  config,
  prefix,
}: {
  config: DeploykitConfig;
  prefix: string;
}): string {
  return `  staging:
    needs: changes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.apps != '[]'
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      fail-fast: false
      matrix:
        app: ${gh("fromJSON(needs.changes.outputs.apps)")}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "staging", flyAppExpr: `"${prefix}$APP-staging"`, singleMachine: true })}`;
}

// ── production: manual, gated deploy ─────────────────────────────────────────
function productionJob({
  config,
  appNames,
  prefix,
}: {
  config: DeploykitConfig;
  appNames: string[];
  prefix: string;
}) {
  return `  production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        app: ${JSON.stringify(appNames)}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "production", flyAppExpr: `"${prefix}$APP-prod"`, singleMachine: false, gated: true })}`;
}

/** A deploy step: ensure the target Fly app exists, stage its secrets, deploy. */
interface DeployStepInput {
  config: DeploykitConfig;
  env: EnvironmentKind;
  /** Shell-quoted expression for the concrete Fly app name. */
  flyAppExpr: string;
  /**
   * Deploy a single machine (`--ha=false`) instead of Fly's HA default of two.
   * Previews/staging run single; production keeps HA.
   */
  singleMachine: boolean;
  gated?: boolean;
}

function deployStep({
  config,
  env,
  flyAppExpr,
  singleMachine,
  gated = false,
}: DeployStepInput) {
  const haFlag = singleMachine ? " --ha=false" : "";
  // Note: inside `if:` the expression is already an implicit ${{ }} context,
  // so matrix.app must be bare here (not wrapped).
  const guard = gated
    ? `        if: github.event.inputs.app == 'all' || github.event.inputs.app == matrix.app\n`
    : "";
  // App secrets are exposed to the script as SECRET_<name> env vars and only
  // ever referenced as shell variables — never expanded into the script text,
  // where a value containing quotes/$ would break the shell (or inject into it).
  // The prefix keeps them from colliding with FLY_API_TOKEN.
  const secretEnvLines = allSecretNames(config)
    .map((s) => `          SECRET_${s}: ${gh(`secrets.${s}`)}\n`)
    .join("");
  // Stateless multi-region: after the deploy, ensure one machine in each extra
  // region. Previews stay single-region (ephemeral, not worth the extra cost).
  // Empty when no extra regions are configured, so single-region output is
  // byte-for-byte unchanged.
  const extras = env === "preview" ? [] : extraRegions(config.provider);
  // Best-effort: the deploy has already succeeded by here, so a transient scale
  // error must not fail the job (set -euo pipefail is active) or skip the rest
  // of the regions — mirror the local firstDeploy path, which warns and
  // continues. `|| echo ::warning::` surfaces it without a red build.
  const scaleBlock = extras.length
    ? `
          # Run in extra regions too (stateless multi-region), best-effort.
          for R in ${extras.join(" ")}; do
            flyctl scale count 1 --region "$R" --app "$FLY_APP" --yes || echo "::warning::could not scale $FLY_APP into $R"
          done`
    : "";
  return `      - name: Deploy (${env})
${guard}        env:
          FLY_API_TOKEN: ${gh("secrets.FLY_API_TOKEN")}
${secretEnvLines}        run: |
          set -euo pipefail
          APP="${gh("matrix.app")}"
          FLY_APP=${flyAppExpr}
          echo "Deploying $APP -> $FLY_APP"
          flyctl status --app "$FLY_APP" >/dev/null 2>&1 || flyctl apps create "$FLY_APP" --org "$FLY_ORG"
          BUILD_ARGS=()
${rootAndSecretsCase({ config, indent: 10 })}
          flyctl deploy . \\
            --config "$ROOT/fly.toml" \\
            --dockerfile "$ROOT/Dockerfile" \\
            --app "$FLY_APP" \\
            --remote-only${haFlag} \${BUILD_ARGS[@]+"\${BUILD_ARGS[@]}"}${scaleBlock}
`;
}

/**
 * Unique secret names across every configured app — runtime secrets *and*
 * build-time vars (both live as GitHub secrets; they differ only in how the
 * deploy step forwards them). Used for the step env block.
 */
function allSecretNames(config: DeploykitConfig): string[] {
  const names = new Set<string>();
  for (const app of Object.values(config.apps)) {
    for (const s of app.secrets) names.add(s);
    for (const b of app.buildEnv ?? []) names.add(b);
  }
  return [...names].sort();
}

/**
 * A shell `case` over the matrix app that sets $ROOT, stages each app's
 * *runtime* secrets (guarded so unset secrets are skipped instead of cleared)
 * and collects its *build-time* vars into the BUILD_ARGS array the deploy
 * command forwards as `--build-arg`. Values are read from the SECRET_<name>
 * env vars set on the step — see deployStep — so their contents never appear
 * in the script text.
 */
function rootAndSecretsCase({
  config,
  indent,
}: {
  config: DeploykitConfig;
  indent: number;
}) {
  const pad = " ".repeat(indent);
  const pad2 = " ".repeat(indent + 2);
  const pad3 = " ".repeat(indent + 4);
  const arms = Object.entries(config.apps).map(([name, app]) => {
    const lines = [`${pad2}${name})`, `${pad3}ROOT="${app.root}"`];
    for (const s of app.secrets) {
      lines.push(
        `${pad3}if [ -n "$SECRET_${s}" ]; then flyctl secrets set --stage --app "$FLY_APP" ${s}="$SECRET_${s}"; fi`,
      );
    }
    for (const b of app.buildEnv ?? []) {
      lines.push(
        `${pad3}if [ -n "$SECRET_${b}" ]; then BUILD_ARGS+=(--build-arg "${b}=$SECRET_${b}"); fi`,
      );
    }
    lines.push(`${pad3};;`);
    return lines.join("\n");
  });
  return [`${pad}case "$APP" in`, ...arms, `${pad}esac`].join("\n");
}
