import type { DeploykitConfig, EnvironmentKind } from "../config.js";

/** Render a GitHub Actions expression: gh("secrets.X") -> "${{ secrets.X }}". */
const gh = (expr: string) => "${{ " + expr + " }}";

export function generateWorkflow(config: DeploykitConfig): string {
  const apps = Object.entries(config.apps);
  const appNames = apps.map(([name]) => name);

  const hasPreview = apps.some(([, a]) => a.environments.preview);
  const hasStaging = apps.some(([, a]) => a.environments.staging);
  const hasProduction = apps.some(([, a]) => a.environments.production);
  const needChanges = hasPreview || hasStaging;

  const jobs: string[] = [];
  if (needChanges) jobs.push(changesJob(config));
  if (hasPreview) jobs.push(previewJob(config), teardownJob(appNames));
  if (hasStaging) jobs.push(stagingJob(config));
  if (hasProduction) jobs.push(productionJob({ config, appNames }));

  return `# Generated by deploykit — CI/CD for a Turbo monorepo on Fly.io.
name: Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy to production ("all" or an app name)'
        default: all

concurrency:
  group: deploy-${gh("github.workflow")}-${gh("github.ref")}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  FLY_ORG: ${config.provider.org}

jobs:
${jobs.join("\n")}`;
}

// ── changes: compute which apps are affected ─────────────────────────────────
function changesJob(config: DeploykitConfig): string {
  const filters = Object.entries(config.apps)
    .map(([name, app]) => {
      const paths = app.watchPaths
        .map((p) => `              - '${p}'`)
        .join("\n");
      return `            ${name}:\n${paths}`;
    })
    .join("\n");

  return `  changes:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    outputs:
      apps: ${gh("steps.filter.outputs.changes")}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
${filters}
`;
}

// ── preview: deploy one app per PR ───────────────────────────────────────────
function previewJob(config: DeploykitConfig): string {
  const flyApp = `"$APP-pr-${gh("github.event.number")}"`;
  return `  preview:
    needs: changes
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && needs.changes.outputs.apps != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${gh("fromJSON(needs.changes.outputs.apps)")}
    concurrency:
      group: preview-${gh("github.event.number")}-${gh("matrix.app")}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "preview", flyAppExpr: flyApp, ha: true })}
      - name: Comment preview URL
        env:
          GH_TOKEN: ${gh("secrets.GITHUB_TOKEN")}
        run: |
          APP="${gh("matrix.app")}"
          URL="https://$APP-pr-${gh("github.event.number")}.fly.dev"
          gh pr comment ${gh("github.event.number")} --repo ${gh("github.repository")} \\
            --body "🚀 Preview for \\\`$APP\\\`: $URL"
`;
}

// ── teardown: destroy preview apps when the PR closes ────────────────────────
function teardownJob(appNames: string[]): string {
  return `  teardown:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${JSON.stringify(appNames)}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destroy preview
        env:
          FLY_API_TOKEN: ${gh("secrets.FLY_API_TOKEN")}
        run: |
          flyctl apps destroy "${gh("matrix.app")}-pr-${gh("github.event.number")}" --yes || true
`;
}

// ── staging: deploy affected apps on merge to main ───────────────────────────
function stagingJob(config: DeploykitConfig): string {
  return `  staging:
    needs: changes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.apps != '[]'
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      fail-fast: false
      matrix:
        app: ${gh("fromJSON(needs.changes.outputs.apps)")}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "staging", flyAppExpr: `"$APP-staging"`, ha: true })}`;
}

// ── production: manual, gated deploy ─────────────────────────────────────────
function productionJob({
  config,
  appNames,
}: {
  config: DeploykitConfig;
  appNames: string[];
}) {
  return `  production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        app: ${JSON.stringify(appNames)}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
${deployStep({ config, env: "production", flyAppExpr: `"$APP-prod"`, ha: false, gated: true })}`;
}

/** A deploy step: ensure the target Fly app exists, stage its secrets, deploy. */
interface DeployStepInput {
  config: DeploykitConfig;
  env: EnvironmentKind;
  /** Shell-quoted expression for the concrete Fly app name. */
  flyAppExpr: string;
  ha: boolean;
  gated?: boolean;
}

function deployStep({ config, env, flyAppExpr, ha, gated = false }: DeployStepInput) {
  const haFlag = ha ? " --ha=false" : "";
  // Note: inside `if:` the expression is already an implicit ${{ }} context,
  // so matrix.app must be bare here (not wrapped).
  const guard = gated
    ? `        if: github.event.inputs.app == 'all' || github.event.inputs.app == matrix.app\n`
    : "";
  return `      - name: Deploy (${env})
${guard}        env:
          FLY_API_TOKEN: ${gh("secrets.FLY_API_TOKEN")}
        run: |
          set -euo pipefail
          APP="${gh("matrix.app")}"
          FLY_APP=${flyAppExpr}
          echo "Deploying $APP -> $FLY_APP"
          flyctl status --app "$FLY_APP" >/dev/null 2>&1 || flyctl apps create "$FLY_APP" --org "$FLY_ORG"
${rootAndSecretsCase({ config, indent: 10 })}
          flyctl deploy . \\
            --config "$ROOT/fly.toml" \\
            --dockerfile "$ROOT/Dockerfile" \\
            --app "$FLY_APP" \\
            --remote-only${haFlag}
`;
}

/**
 * A shell `case` over the matrix app that sets $ROOT and stages each app's
 * secrets (guarded so unset secrets are skipped instead of cleared).
 */
function rootAndSecretsCase({
  config,
  indent,
}: {
  config: DeploykitConfig;
  indent: number;
}) {
  const pad = " ".repeat(indent);
  const pad2 = " ".repeat(indent + 2);
  const pad3 = " ".repeat(indent + 4);
  const arms = Object.entries(config.apps).map(([name, app]) => {
    const lines = [`${pad2}${name})`, `${pad3}ROOT="${app.root}"`];
    for (const s of app.secrets) {
      const ref = gh(`secrets.${s}`);
      lines.push(
        `${pad3}if [ -n "${ref}" ]; then flyctl secrets set --stage --app "$FLY_APP" ${s}="${ref}"; fi`,
      );
    }
    lines.push(`${pad3};;`);
    return lines.join("\n");
  });
  return [`${pad}case "$APP" in`, ...arms, `${pad}esac`].join("\n");
}
