import { defineConfig } from "@alminabrulic/deploykit";

// Generated by `deploykit init` — the source of truth for your CI/CD setup.
// Edit this file (plain data only — no variables or expressions), then run
// `deploykit generate` to regenerate the Dockerfiles, fly.toml files and
// workflow from it. Formatting it however your repo formats TypeScript is fine.
export default defineConfig({
  "tool": "turbo",
  "packageManager": "pnpm",
  "nodeVersion": "20",
  "provider": {
    "type": "fly",
    "org": "acme",
    "region": "iad",
    "regions": [
      "iad",
      "lhr"
    ]
  },
  "apps": {
    "web": {
      "root": "apps/web",
      "packageName": "@acme/web",
      "framework": "react-router",
      "serve": "server",
      "port": 3000,
      "internalDeps": [
        "@acme/ui",
        "@acme/database"
      ],
      "watchPaths": [
        "apps/web/**",
        "packages/ui/**",
        "packages/database/**"
      ],
      "environments": {
        "preview": {
          "name": "acme-web-pr-{pr}",
          "trigger": "pr"
        },
        "staging": {
          "name": "acme-web-staging",
          "trigger": "push:main"
        },
        "production": {
          "name": "acme-web-prod",
          "trigger": "manual",
          "hostname": "shop.example.com"
        }
      },
      "secrets": [
        "DATABASE_URL",
        "SESSION_SECRET"
      ],
      "startCommand": [
        "node",
        "node_modules/@react-router/serve/bin.js",
        "./build/server/index.js"
      ],
      "prisma": [
        {
          "packageName": "@acme/database",
          "root": "packages/database",
          "schema": "prisma/schema.prisma",
          "hasConfig": false
        }
      ],
      "buildEnv": [
        "VITE_API_URL"
      ]
    },
    "marketing": {
      "root": "apps/marketing",
      "packageName": "@acme/marketing",
      "framework": "astro",
      "serve": "static",
      "port": 8080,
      "internalDeps": [
        "@acme/ui"
      ],
      "watchPaths": [
        "apps/marketing/**",
        "packages/ui/**"
      ],
      "environments": {
        "preview": {
          "name": "acme-marketing-pr-{pr}",
          "trigger": "pr"
        },
        "staging": {
          "name": "acme-marketing-staging",
          "trigger": "push:main"
        }
      },
      "secrets": [],
      "outputDir": "dist"
    }
  },
  "namePrefix": "acme",
  "cloudflare": {
    "zone": "example.com",
    "proxied": true,
    "ssl": "strict",
    "alwaysUseHttps": true,
    "minTlsVersion": "1.2",
    "security": true,
    "cache": true
  }
});
