import { exec } from "./util/exec.js";

export interface PrResult {
  ok: boolean;
  url?: string;
  detail?: string;
}

const BRANCH = "deploykit/ci-setup";

const PR_BODY = [
  "Automated CI/CD setup generated by `deploykit`.",
  "",
  "- PR preview environments (auto torn down on close)",
  "- Staging deploy on merge to `main`",
  "- Production deploy behind manual approval",
  "",
  "Review the generated Dockerfiles, fly.toml files and workflow before merging.",
].join("\n");

const fail = (detail: string) => ({ ok: false, url: undefined, detail });
const succeed = (url: string) => ({ ok: true, url, detail: undefined });

/**
 * Commit the generated files on a branch and open a PR. Assumes `gh` is
 * authenticated and the repo has a GitHub remote.
 */
export async function openPr({ cwd, paths }: { cwd: string; paths: string[] }) {
  if (paths.length === 0) return fail("nothing to commit");

  const onBranch = await switchToBranch(cwd);
  if (!onBranch.ok) return fail(onBranch.detail ?? "could not switch branch");

  const add = await exec({ cmd: "git", args: ["add", ...paths], cwd });
  if (add.code !== 0) return fail(`git add failed: ${add.stderr.trim()}`);

  const commit = await exec({
    cmd: "git",
    args: ["commit", "-m", "ci: add deploykit CI/CD"],
    cwd,
  });
  if (commit.code !== 0) return fail(`git commit failed: ${commit.stderr.trim()}`);

  const push = await exec({
    cmd: "git",
    args: ["push", "-u", "origin", BRANCH],
    cwd,
  });
  if (push.code !== 0) return fail(`git push failed: ${push.stderr.trim()}`);

  const pr = await exec({
    cmd: "gh",
    args: ["pr", "create", "--title", "ci: add deploykit CI/CD", "--body", PR_BODY],
    cwd,
  });
  if (pr.code !== 0) return fail(`gh pr create failed: ${pr.stderr.trim()}`);

  return succeed(pr.stdout.trim());
}

/** Create the setup branch, or switch to it if it already exists. */
async function switchToBranch(cwd: string) {
  const created = await exec({ cmd: "git", args: ["checkout", "-b", BRANCH], cwd });
  if (created.code === 0) return { ok: true, detail: undefined };

  const switched = await exec({ cmd: "git", args: ["checkout", BRANCH], cwd });
  if (switched.code === 0) return { ok: true, detail: undefined };

  return { ok: false, detail: `could not create/switch branch: ${created.stderr.trim()}` };
}
