import { rmSync } from "node:fs";
import { join } from "node:path";
import { type GeneratedFile, writeFiles } from "./generate/index.js";
import { exec, tryExec } from "./util/exec.js";

export interface PrResult {
  ok: boolean;
  url?: string;
  detail?: string;
  /** Branch the working tree was returned to, when it was switched back. */
  restoredTo?: string;
}

const BRANCH = "deploykit/ci-setup";
const TITLE = "ci: add deploykit CI/CD";

const PR_BODY = [
  "Automated CI/CD setup generated by `deploykit`.",
  "",
  "- PR preview environments (auto torn down on close)",
  "- Staging deploy on merge to `main`",
  "- Production deploy behind manual approval",
  "",
  "Review the generated Dockerfiles, fly.toml files and workflow before merging.",
].join("\n");

/** Injected `gh` seams, so the git flow is testable without a real GitHub. */
export interface PrDeps {
  /** URL of an already-open PR for the branch, or null if none. */
  findOpenPr: (branch: string, cwd: string) => Promise<string | null>;
  /** Open a PR; returns the new PR URL, or null on failure (with `detail`). */
  createPr: (cwd: string) => Promise<{ url: string | null; detail?: string }>;
}

const defaultDeps: PrDeps = {
  findOpenPr: (branch, cwd) =>
    tryExec({
      cmd: "gh",
      args: [
        "pr",
        "list",
        "--head",
        branch,
        "--state",
        "open",
        "--json",
        "url",
        "--jq",
        ".[0].url // empty",
      ],
      cwd,
    }).then((out) => out || null),
  createPr: async (cwd) => {
    const pr = await exec({
      cmd: "gh",
      args: ["pr", "create", "--title", TITLE, "--body", PR_BODY],
      cwd,
    });
    return pr.code === 0
      ? { url: pr.stdout.trim() }
      : { url: null, detail: `gh pr create failed: ${pr.stderr.trim()}` };
  },
};

/**
 * Commit the generated files on a branch and open a PR. Assumes `gh` is
 * authenticated and the repo has a GitHub remote. The working tree is returned
 * to the branch the user started on — success or failure — so the run doesn't
 * leave them stranded on the setup branch.
 *
 * Safe to re-run: an existing setup branch is reused (not recreated), the files
 * are re-materialised from `files` so their content is authoritative, an
 * unchanged re-run skips the commit instead of failing on "nothing to commit",
 * and an already-open PR for the branch is reused instead of erroring on a
 * duplicate. The caller's other uncommitted work is never force-discarded.
 */
export async function openPr({
  cwd,
  files,
  deps,
}: {
  cwd: string;
  files: GeneratedFile[];
  deps?: Partial<PrDeps>;
}): Promise<PrResult> {
  if (files.length === 0) return { ok: false, detail: "nothing to commit" };
  const { findOpenPr, createPr } = { ...defaultDeps, ...deps };
  const paths = files.map((f) => f.path);

  // Remember where the user was; "HEAD" means detached (nothing to restore to).
  const original = await tryExec({
    cmd: "git",
    args: ["rev-parse", "--abbrev-ref", "HEAD"],
    cwd,
  });

  const restore = async (): Promise<string | undefined> => {
    if (!original || original === "HEAD" || original === BRANCH)
      return undefined;
    const res = await exec({ cmd: "git", args: ["checkout", original], cwd });
    return res.code === 0 ? original : undefined;
  };
  const fail = async (detail: string): Promise<PrResult> => ({
    ok: false,
    detail,
    restoredTo: await restore(),
  });

  const onBranch = await switchToBranch({ cwd, paths });
  if (!onBranch.ok) return fail(onBranch.detail ?? "could not switch branch");

  // Re-materialise the generated files on the branch so their content is
  // authoritative — this makes a re-run with a changed config update the branch
  // rather than silently keeping stale files, and makes an unchanged re-run a
  // clean no-op (the diff below stays empty).
  writeFiles({ files, cwd, force: true });

  const add = await exec({ cmd: "git", args: ["add", ...paths], cwd });
  if (add.code !== 0) return fail(`git add failed: ${add.stderr.trim()}`);

  // `git diff --cached --quiet` exits 0 when nothing is staged, 1 when there is
  // a diff. Skip the commit on a no-op re-run instead of failing on it.
  const staged = await exec({
    cmd: "git",
    args: ["diff", "--cached", "--quiet"],
    cwd,
  });
  if (staged.code !== 0) {
    const commit = await exec({
      cmd: "git",
      args: ["commit", "-m", TITLE],
      cwd,
    });
    if (commit.code !== 0)
      return fail(`git commit failed: ${commit.stderr.trim()}`);
  }

  const push = await exec({
    cmd: "git",
    args: ["push", "-u", "origin", BRANCH],
    cwd,
  });
  if (push.code !== 0) return fail(`git push failed: ${push.stderr.trim()}`);

  // Reuse an open PR for this branch rather than erroring on a duplicate.
  const existing = await findOpenPr(BRANCH, cwd);
  if (existing) return { ok: true, url: existing, restoredTo: await restore() };

  const pr = await createPr(cwd);
  if (!pr.url) return fail(pr.detail ?? "gh pr create failed");

  return { ok: true, url: pr.url, restoredTo: await restore() };
}

/**
 * Create the setup branch, or switch to it if it already exists. When it exists,
 * the generated files this run just wrote are untracked and would block the
 * checkout ("untracked working tree files would be overwritten"); remove them
 * first — they are re-written from `files` immediately after the switch, so
 * nothing is lost, and only deploykit's own generated paths are touched.
 */
async function switchToBranch({
  cwd,
  paths,
}: {
  cwd: string;
  paths: string[];
}) {
  const created = await exec({
    cmd: "git",
    args: ["checkout", "-b", BRANCH],
    cwd,
  });
  if (created.code === 0) return { ok: true, detail: undefined };

  for (const p of paths) rmSync(join(cwd, p), { force: true });
  const switched = await exec({ cmd: "git", args: ["checkout", BRANCH], cwd });
  if (switched.code === 0) return { ok: true, detail: undefined };

  return {
    ok: false,
    detail: `could not create/switch branch: ${created.stderr.trim()}`,
  };
}
