import { exec, tryExec } from "./util/exec.js";

export interface PrResult {
  ok: boolean;
  url?: string;
  detail?: string;
  /** Branch the working tree was returned to, when it was switched back. */
  restoredTo?: string;
}

const BRANCH = "deploykit/ci-setup";

const PR_BODY = [
  "Automated CI/CD setup generated by `deploykit`.",
  "",
  "- PR preview environments (auto torn down on close)",
  "- Staging deploy on merge to `main`",
  "- Production deploy behind manual approval",
  "",
  "Review the generated Dockerfiles, fly.toml files and workflow before merging.",
].join("\n");

/**
 * Commit the generated files on a branch and open a PR. Assumes `gh` is
 * authenticated and the repo has a GitHub remote. The working tree is returned
 * to the branch the user started on — success or failure — so the run doesn't
 * leave them stranded on the setup branch.
 */
export async function openPr({
  cwd,
  paths,
}: {
  cwd: string;
  paths: string[];
}): Promise<PrResult> {
  if (paths.length === 0) return { ok: false, detail: "nothing to commit" };

  // Remember where the user was; "HEAD" means detached (nothing to restore to).
  const original = await tryExec({
    cmd: "git",
    args: ["rev-parse", "--abbrev-ref", "HEAD"],
    cwd,
  });

  const restore = async (): Promise<string | undefined> => {
    if (!original || original === "HEAD" || original === BRANCH)
      return undefined;
    const res = await exec({ cmd: "git", args: ["checkout", original], cwd });
    return res.code === 0 ? original : undefined;
  };
  const fail = async (detail: string): Promise<PrResult> => ({
    ok: false,
    detail,
    restoredTo: await restore(),
  });

  const onBranch = await switchToBranch(cwd);
  if (!onBranch.ok)
    return { ok: false, detail: onBranch.detail ?? "could not switch branch" };

  const add = await exec({ cmd: "git", args: ["add", ...paths], cwd });
  if (add.code !== 0) return fail(`git add failed: ${add.stderr.trim()}`);

  const commit = await exec({
    cmd: "git",
    args: ["commit", "-m", "ci: add deploykit CI/CD"],
    cwd,
  });
  if (commit.code !== 0)
    return fail(`git commit failed: ${commit.stderr.trim()}`);

  const push = await exec({
    cmd: "git",
    args: ["push", "-u", "origin", BRANCH],
    cwd,
  });
  if (push.code !== 0) return fail(`git push failed: ${push.stderr.trim()}`);

  const pr = await exec({
    cmd: "gh",
    args: [
      "pr",
      "create",
      "--title",
      "ci: add deploykit CI/CD",
      "--body",
      PR_BODY,
    ],
    cwd,
  });
  if (pr.code !== 0) return fail(`gh pr create failed: ${pr.stderr.trim()}`);

  return { ok: true, url: pr.stdout.trim(), restoredTo: await restore() };
}

/** Create the setup branch, or switch to it if it already exists. */
async function switchToBranch(cwd: string) {
  const created = await exec({
    cmd: "git",
    args: ["checkout", "-b", BRANCH],
    cwd,
  });
  if (created.code === 0) return { ok: true, detail: undefined };

  const switched = await exec({ cmd: "git", args: ["checkout", BRANCH], cwd });
  if (switched.code === 0) return { ok: true, detail: undefined };

  return {
    ok: false,
    detail: `could not create/switch branch: ${created.stderr.trim()}`,
  };
}
